version: '3.9'

services:
  rabbit: 
    image: rabbitmq:latest
    network_mode: "host"

  postgres:
    image: postgres:14.2
    environment:
      - POSTGRES_USER=staging
      - POSTGRES_PASSWORD=staging
    network_mode: "host"