// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type ReplenishTheBalanceOrErrorPayload interface {
	IsReplenishTheBalanceOrErrorPayload()
}

type WithdrawMoneyOrErrorPayload interface {
	IsWithdrawMoneyOrErrorPayload()
}

type ErrorPayload struct {
	Message string `json:"message"`
}

func (ErrorPayload) IsWithdrawMoneyOrErrorPayload()       {}
func (ErrorPayload) IsReplenishTheBalanceOrErrorPayload() {}

type ReplenishTheBalanceInput struct {
	UserID int `json:"userID"`
	Amount int `json:"Amount"`
}

type ReplenishTheBalancePayload struct {
	ReplenishmentAmount float64 `json:"replenishmentAmount"`
	Balance             float64 `json:"balance"`
}

func (ReplenishTheBalancePayload) IsReplenishTheBalanceOrErrorPayload() {}

type WithdrawMoneyInput struct {
	UserID int `json:"userID"`
	Amount int `json:"Amount"`
}

type WithdrawMoneyPayload struct {
	AmountWrittenOff float64 `json:"amountWrittenOff"`
	Balance          float64 `json:"balance"`
}

func (WithdrawMoneyPayload) IsWithdrawMoneyOrErrorPayload() {}
