// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type RegisterUserOrErrorPayload interface {
	IsRegisterUserOrErrorPayload()
}

type ReplenishTheBalanceOrErrorPayload interface {
	IsReplenishTheBalanceOrErrorPayload()
}

type WithdrawMoneyOrErrorPayload interface {
	IsWithdrawMoneyOrErrorPayload()
}

type ErrorPayload struct {
	Message string `json:"message"`
}

func (ErrorPayload) IsRegisterUserOrErrorPayload()        {}
func (ErrorPayload) IsWithdrawMoneyOrErrorPayload()       {}
func (ErrorPayload) IsReplenishTheBalanceOrErrorPayload() {}

type RegisterUserInput struct {
	Name *string `json:"name"`
}

type RegisterUserPayload struct {
	User *User `json:"user"`
}

func (RegisterUserPayload) IsRegisterUserOrErrorPayload() {}

type ReplenishTheBalanceInput struct {
	UserID int `json:"userID"`
	Amount int `json:"amount"`
}

type ReplenishTheBalancePayload struct {
	ReplenishmentAmount int `json:"replenishmentAmount"`
	UserID              int `json:"userID"`
}

func (ReplenishTheBalancePayload) IsReplenishTheBalanceOrErrorPayload() {}

type WithdrawMoneyInput struct {
	UserID int `json:"userID"`
	Amount int `json:"amount"`
}

type WithdrawMoneyPayload struct {
	AmountWrittenOff int `json:"amountWrittenOff"`
	UserID           int `json:"userID"`
}

func (WithdrawMoneyPayload) IsWithdrawMoneyOrErrorPayload() {}
